Category.create(name: "Ice Breaker")
Category.create(name: "Active Team Initiative")
Category.create(name: "Problem Solving Initiative")
Category.create(name: "Trust Activity")
Category.create(name: "Debrief")
